### ISSUE TITLE
Issue while reading PMML generated from SAS e Miner

### ISSUE THREAD

**Issue by NikhilSingla-88** [jpmml/jpmml-cascading#10]
Hi,

I am getting below exception while trying to use this code  while reading output PMML from SAS EM. 

Kindly let me know if require more informaiton.

Regards,
Nikhil

**Comment by vruusmann** [comment]
Please see the following StackOverflow thread:
https://stackoverflow.com/questions/33003359/fmtwidth-error-while-using-jpmml-to-evaluate-a-sas-produced-pmml-file

In short, SAS EM is generating invalid PMML documents. They can be corrected using the `org.jpmml.sas.visitors.ExpressionCorrector` Visitor class.

**Comment by NikhilSingla-88** [comment]
Thanks..!! That issue is fixed. You should include that patch in this code. Facing new issue org.jpmml.evaluator.DuplicateValueException (at or around line 93): AnyCInput

**Comment by vruusmann** [comment]
> You should include that patch in this code.

That would be unreasonable maintenance burden. Sure, it should be properly documented (possibly at the JPMML-Evaluator project level), but the JPMML-Cascading library just can't rewrite every PMML document on a "just in case" basis.

You should consider setting up a local workflow, where all "raw" SAS EM PMML documents are rewritten (eg. using a dedicated command-line application, such as `org.jpmml.model.CopyExample`) before they are passed on to JPMML-Cascading.

> Facing new issue org.jpmml.evaluator.DuplicateValueException (at or around line 93): AnyCInput

Like the name of the exception class suggests - the PMML document is attempting to declare the value of the `AnyCInput` field more than once, which is an error condition. I need to see the problematic PMML document before I can suggest a fix/workaround. Can you attach it here, or send it to my e-mail?
