### ISSUE TITLE
How to set the Hadoop queue name in jpmml cascading.

### ISSUE THREAD

**Issue by nitinmahesh** [jpmml/jpmml-cascading#3]
I am trying to execute pmml model using cascading framework in jpmml cascading library provided in this project https://github.com/jpmml/jpmml-cascading

I have followed all the steps and was able to generate the example-1.2-SNAPSHOT-job.jar using mvn clean install command.

However when I am executing the same jar using the below command :

hadoop jar example-1.2-SNAPSHOT-job.jar /tmp/cascading/model.pmml file:///tmp/cascading/input.csv file:///tmp/cascading/output
I am getting below exceptions for not having the rights to submit the job on DEFAULT queue as default queue in our hadoop cluster is blocked for admin purpose only, normal user can not run the hadoop job without providing the queue name.

Exception:
16/01/06 04:41:37 ERROR ipc.FailoverRPC: FailoverProxy: Failing this Call: submitJob for error(RemoteException): org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.AccessControlException): **User test cannot perform operation SUBMIT_JOB on queue default.**
 Please run "hadoop queue -showacls" command to find the queues you have access to .
    at org.apache.hadoop.mapred.ACLsManager.checkAccess(ACLsManager.java:179)
    at org.apache.hadoop.mapred.ACLsManager.checkAccess(ACLsManager.java:136)
    at org.apache.hadoop.mapred.ACLsManager.checkAccess(ACLsManager.java:113)
    at org.apache.hadoop.mapred.JobTracker.submitJob(JobTracker.java:4524)
    at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.ipc.WritableRpcEngine$Server$WritableRpcInvoker.call(WritableRpcEngine.java:481)
    at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:928)
    at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2000)
    at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1996)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1566)
    at org.apache.hadoop.ipc.Server$Handler.run(Server.java:1994)
I am not able to see where to provide the hadoop job queue in the repository.

Updated main class that i am trying for the last 24 hours to run on my MapR cluster.

``` javascript

public class Main {

    static
    public void main(String... args) throws Exception {

        if(args.length != 3){
            System.err.println("Usage: hadoop jar job.jar <PMML file> <HFS source> <HFS sink>");

            System.exit(-1);
        }

        Properties properties = new Properties();

/*Putting all the random job queue name setting property to handle in Hadoop 1 and as well as Hadoop 2
*/
        properties.put("mapreduce.job.queuename", "test2");
        properties.put("mapred.job.queue.name", "test2");
        properties.setProperty("mapreduce.job.queuename", "test2");
        properties.setProperty("mapred.job.queue.name", "test2");

/*Now trying to set the jobconf in HadoopPlanner */
        JobConf conf = new JobConf(Main.class);

        conf.set("mapred.job.queue.name", "test2");

        HadoopPlanner.copyJobConf(properties, conf);


        AppProps.setApplicationJarClass(properties, Main.class);

        FlowConnector connector = new HadoopFlowConnector(properties);

        PMML pmml;

        InputStream is = new FileInputStream(args[0]);

        try {
            Source source = ImportFilter.apply(new InputSource(is));

            pmml = JAXBUtil.unmarshalPMML(source);
        } finally {
            is.close();
        }

        pmml.accept(new LocatorTransformer());

        PMMLManager pmmlManager = new PMMLManager(pmml);

        ModelEvaluator<?> modelEvaluator = (ModelEvaluator<?>)pmmlManager.getModelManager(ModelEvaluatorFactory.getInstance());
        modelEvaluator.verify();

        FlowDef flowDef = FlowDef.flowDef();

        Tap source = new Hfs(new TextDelimited(true, ","), args[1]);
        flowDef = flowDef.addSource("source", source);

        Tap sink = new Hfs(new TextDelimited(true, ","), args[2]);
        flowDef = flowDef.addSink("sink", sink);

        PMMLPlanner pmmlPlanner = new PMMLPlanner(modelEvaluator);
        pmmlPlanner.setRetainOnlyActiveFields();

        flowDef = flowDef.addAssemblyPlanner(pmmlPlanner);

//Trying to print out all the property keys and values before setting the job to run.
        Map<Object,Object> propLast = connector.getProperties();
        if(propLast instanceof Properties) {
            Properties i$ = (Properties)propLast;
            Set entry = i$.stringPropertyNames();
            Iterator i$1 = entry.iterator();

            while(i$1.hasNext()) {
                String key = (String)i$1.next();
                System.out.println("key: " +key + "<- value: " + i$.getProperty(key)+"<-");
            }
        } else {
            Iterator i$2 = propLast.entrySet().iterator();

            while(i$2.hasNext()) {
                Map.Entry entry1 = (Map.Entry)i$2.next();
                if(entry1.getValue() != null) {
                    System.out.println("key: " + entry1.getKey().toString() + "<- value: " + entry1.getValue().toString() + "<-");
                }
            }
        }
        Flow<?> flow = connector.connect(flowDef);

        flow.complete();
    }
}
```

**Comment by nitinmahesh** [comment]
I have found the similar issue in Scalding framework as well link : https://github.com/twitter/scalding/issues/56

I hope this could be solvable in Cascading framework (if at all this is the issue).

Hoping to see some answer on this.

**Comment by vruusmann** [comment]
This issue affects generic Apache Hadoop and/or Cascading layers. It has nothing to do with the more specific JPMML-Cascading layer.

Could you create a simple "Hello World"-type of Cascading application and run it successfully on your Apache Hadoop cluster? There is no need to bring in JPMML-Cascading library, because it is blissfully unaware about its execution environment, and cannot affect it in any way.

You could post this question to Cascading mailing list (eg. https://groups.google.com/forum/#!forum/cascading-user). It is clearly off-topic here.

Also, please note that the purpose of the JPMML-Cascading example application is to demonstrate basic JPMML-Cascading library use. It is not intended for production use.

**Comment by nitinmahesh** [comment]
So how do you propose to distribute the jpmml processing in the hadoop cluster, as right now what i am aware of that jpmml-evaluator is single threaded locally running java program. I really wanted to use the jpmml evaluator on a hadoop cluster in a distributed manner.

**Comment by vruusmann** [comment]
JPMML-Evaluator is a simple and self-contained Java library for evaluating PMML models on the Java platform, ranging from mobile devices (Android) to Big Data platforms (Apache Hadoop). And, by design, it has full support for multi-threading.

I have no idea what Big Data platform works best in your use case. But the JPMML-Evaluator library is definitely not the limiting factor.

**Comment by nitinmahesh** [comment]
I mean how can i use this jpmml-evaluator library in Hadoop distributed manner? 

As right now this is being invoked using java -cp example-1.1-SNAPSHOT.jar  org.jpmml.evaluator.EvaluationExample --input /tmp/input.csv --output /tmp/output --model /tmp/test.pmml.. 
So by this way i can say that it is still running through java command and not utilizing the hadoop distribution processing that is being parallely processed across the cluster.

I know jpmml-evaluator is full supported for multi-threading but in theory if you run jar file using java command in hadoop cluster it still process the file on local node only in separate way.

How can i use the same jpmml-evaluator library in hadoop jar example-job.jar pmml.file input.csv output.csv way, as right now it is being provided only in jpmml-cascading project only. Where i can see the mapper/reducer output and processing.

If you know how can i use the jpmml-evaluator in Hadoop. I hope i have cleared my understanding towards using jpmml-cascading project.

**Comment by vruusmann** [comment]
The integration pattern is:
1) Apache Hadoop
2) ???
3) JPMML-Evaluator

The choice of the middleware layer (ie. Apache Hadoop abstraction) depends on what you data analysts are comfortable working with. JPMML-Cascading uses Cascading, JPMML-Pig uses Apache Pig, JPMML-Hive uses Apache Hive etc.

Have you checked out the [JPMML-Piglet](https://github.com/jpmml/jpmml-piglet) project (a rewrite of the JPMML-Pig project)? It scores a Pig datatable (loaded from a CSV file) with a PMML model. You could dump the resulting Pig datatable to a new CSV file. Here, Apache Pig takes care of distributing and coordinating the work across your Apache Hadoop cluster.

**Comment by nitinmahesh** [comment]
Thanks for the suggestion, i would try to run JPMML-Piglet , also do we have JPMML-Hadoop or JPMML-HDFS which uses Apache Hadoop and HDFS respectively.

And do we have any benchmarking standards for JPMML-Evaluator for different middleware layer and for which type of models which layer would be good in terms of performance.

**Comment by vruusmann** [comment]
Very likely, there will be no JPMML-Hadoop or JPMML-HDFS projects, because that's a too low abstraction level. Who writes "native" Java MR applications nowadays?

The choice of the middleware should be based on familiarity (when already knowing one) and ease of use (when deciding to learn one), not hypothetical performance differences. If you need performance, then consider moving to Apache Spark with the help of JPMML-Spark project.

**Comment by nitinmahesh** [comment]
Ahh i see, that's very true its hard to go to low level.

I would definitely try JPMML-Spark as that is we are ready in production and JPMML-Piglet(thats offcourse supported in production).

Just a quick question regarding JPMML-Evaluator, will that be really good for 100 million records scoring?

**Comment by vruusmann** [comment]
The performance depends on the complexity of models. My laptop can perform 100 million evaluations with the `DecisionTreeIris.pmml` model in about two minutes.

Locking this conversation now.
