### ISSUE TITLE
JPMML - Cascading Issue

### ISSUE THREAD

**Issue by vmuraliraju** [jpmml/jpmml-cascading#8]
Hi,

When we execute on Apache 1.2.0 hadoop environment. It is working fine. 

When we execute on Apache 2.X hadoop environment, we are getting node manage not able to execute.

**Comment by vruusmann** [comment]
Please fix your Apache Hadoop configuration.

**Comment by vmuraliraju** [comment]
code will execute on 2.x Hadoop version, I need confirmation
